POST http://localhost:4000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation addNote($note: NoteArgs){
  addNote(note: $note) {
    title
    zettelId
    text
    tags
    wikilinks
    backlinks { title zettelId }
  }
}

{
  "note": {
    "title": "ApolloClient",
    "zettelId": "4321213423",
    "text": "[[moikkelis]] [[anarchy]] #life"
  }
}

###

POST http://localhost:4000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation editNote($note: NoteArgs){
  editNote(
    note: $note
  ) {
    title
    zettelId
    text
    tags
    userId
    wikilinks # { title zettelId }
    # backlinks { title zettelId }
  }
}

{
  "note": {
    "title": "communism12124",
    "zettelId": "48739120",
    "text": "[[moikkelis]] [[anarchy]] #life"
  }
}

###
POST http://localhost:4000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query allNotes {
  allNotes {
    title
    zettelId
    tags
    text
    wikilinks # { title zettelId }
    backlinks {
      title
      zettelId
    }
  }
}

###

POST http://localhost:4000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query findNote($query: String!) {
  findNote(query: $query) {
    title
    zettelId
    tags
    text
  }
}

{
  "query": "moikkelis"
}

###

POST http://localhost:4000/
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query findNotes($title: String, $zettelId: String, $tag: String) {
  findNotes(
    title: $title
    zettelId: $zettelId
    tag: $tag
  ) {
    title
    zettelId
    tags
    text
  }
}

{
  # "zettelId": "1234"
  # "title": "communism",
  # "tag": "life"
}