@baseUrl = http://localhost:4000/graphql
@authentication = Bearer {{LOGIN.response.body.data.login.token}}

POST {{baseUrl}}
Content-Type: application/json
Authorization: {{authentication}}
X-REQUEST-TYPE: GraphQL

mutation addNote($note: NoteArgs){
  addNote(note: $note) {
    title
    zettelId
    text
    tags
    wikilinks
    backlinks {
      title
    }
  }
}

{
  "note": {
    "title": "newest note",
    "zettelId": "4132222292283428902732",
    "text": "[[moikkelis]] [[anarchy]] [[ApolloClient]] #apollo"
  }
}

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: {{authentication}}
X-REQUEST-TYPE: GraphQL

mutation editNote($note: NoteArgs){
  editNote(
    note: $note
  ) {
    title
    zettelId
    text
    tags
    userId
    wikilinks # { title zettelId }
  }
}

{
  "note": {
    "title": "wikilink",
    "zettelId": "100003",
    "text": "[[moikkelis]] [[anarchy]] [[ApolloClient]] #life"
  }
}

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: {{authentication}}
X-REQUEST-TYPE: GraphQL

query allNotes {
  allNotes {
    title
    zettelId
    # tags
    # text
    # wikilinks
    # backlinks {
    #   title
    # }
  }
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZGU2IiwiaWQiOiJqYWsyNWwzMjEya2psMzRkc2FmIiwiaWF0IjoxNjI1MTY1MDk2fQ.xtKZdUDGbTELrvjWpa6-sbVnoqpNhAHxmTPYR1sawZY
X-REQUEST-TYPE: GraphQL

query findNote($query: String!) {
  findNote(query: $query) {
    title
    zettelId
    tags
    text
  }
}

{
  "query": "cosmos"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZGU2IiwiaWQiOiJqYWsyNWwzMjEya2psMzRkc2FmIiwiaWF0IjoxNjI1MTY1MDk2fQ.xtKZdUDGbTELrvjWpa6-sbVnoqpNhAHxmTPYR1sawZY

query findNotes($title: String, $zettelId: String, $tag: String) {
  findNotes(
    title: $title
    zettelId: $zettelId
    tag: $tag
  ) {
    title
    zettelId
    tags
    text
  }
}

{
  # "zettelId": "1234"
  # "title": "communism",
  # "tag": "life"
}

###


POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation register($username: string!, $password: string!) {
  register(
    username: $username
    password: $password
  ) {
    token
  }
}

{
  "username": "arde10",
  "password": "kissa3"
}

### 

# @name LOGIN

POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZGUxMCIsImlkIjoiNjBlZTA0ZTQxMGVkOTc2MTZmZjZjNjVhIiwiaWF0IjoxNjI2MjExNTU2LCJleHAiOjE2MjYyMTUxNTZ9.RKL98Z5vtxV8qkKsmRnMZGkVBz_JY87FxPVIrOkvwmQ
X-REQUEST-TYPE: GraphQL

mutation login($username: String!, $password: String!) {
  login(
    username: $username
    password: $password
  ) {
    token
  }
}

{
  "username": "igno",
  "password": "moikkelis"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZGUxMCIsImlkIjoiNjBlZTBlNGI2MWI3ZTk2ZjBkZGM4NWI5IiwiaWF0IjoxNjI2MjE3NjY2LCJleHAiOjE2MjYyMjEyNjZ9.jzFv_5LXCg37EeEKD3-kRyNrgJnGhvXPvettWrBqbYU
X-REQUEST-TYPE: GraphQL

query findLatestNotes {
  findLatestNotes {
    title
  }
}


###

POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZGUxMCIsImlkIjoiNjBmMDY1Mzg2NDNhNzY2NjI3NDg0ZTc2IiwiaWF0IjoxNjI2MzY3Mjg4LCJleHAiOjE2MjYzNzA4ODh9.Q1jNMkV30rab3yiZaYXeqy4qSYuGUCACb-pDOHJV_7k
X-REQUEST-TYPE: GraphQL

query allTags {
  allTags
}

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: {{authentication}}
X-REQUEST-TYPE: GraphQL

query SearchNotes($input: String!) {
  searchNotes(input: $input) {
    # title
    # zettelId
    # tags
    modified
  }
}

{
  "input": ""
}